# https://taskfile.dev
version: '3'
vars:
  BINFILE: zabbix-cli

includes:
  dev: ./Taskfile_dev.yml

tasks:

  default:
    desc: "List tasks"
    cmds:
      - task -a

  binary:
    desc: "Build binary"
    cmds:
      - go generate ./...
      - CGO_ENABLED=0 go build -o {{ .BINFILE }} cmd/*.go
    # silent: true

  linter:
    desc: "Run linter"
    cmds:
      - golangci-lint run

  tests:
    desc: "Run tests"
    dir: tests
    cmds:
      - venom run testsuite.yml --output-dir="log" --stop-on-failure

  godoc:
    desc: "godoc server"
    cmds:
      - go install golang.org/x/tools/cmd/godoc@latest
      - echo "http://localhost:6060/pkg/github.com/sgaunet/zabbix-cli/"
      - godoc -http=:6060
  
  snapshot:
    desc: "Create snapshot"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --skip validate

  coverage:
    desc: "Run the tests with coverage"
    cmds:
      - go test -coverpkg=github.com/sgaunet/zabbix-cli/cmd,github.com/sgaunet/zabbix-cli/pkg/config,github.com/sgaunet/zabbix-cli/pkg/zabbix -coverprofile=profile.cov ./...
      - go tool cover -func profile.cov
      - rm profile.cov